### ISSUE TITLE
Outros modelos de Arduino

### ISSUE THREAD

**Issue by jjcodes78** [rennancockles/hiduino#1]
Ola Rennan!

Gostei muito do projeto no entanto me surgiu uma dúvida:

Este firmware só serve para o UNO ou os demais (Nano, Micro) se utilizarem o atmega16u2 podem ser modificados também?

Abraço!

**Comment by rennancockles** [comment]
Não cheguei a testar o firmware em outros arduinos. Se eles possuem o atmega 16u2, também podem ser utilizados como interface HID, porém não sei se a mesma firmware servirá ou se terá que arrumar uma firmware diferente para eles.

**Comment by jjcodes78** [comment]
como eu crio ou modifico a firmware para que funcione nos modelos menores?

obrigado!

**Comment by jjcodes78** [comment]
tem a intenção de disponibilizar firmwares para os outros modelos? ou ensinar​ como criar elas?

vim pelo seu curso do rubber duck do guardweb e gostei bastante.

**Comment by rennancockles** [comment]
Alguns modelos, como o arduino pro micro e o arduino leonardo, não precisam alterar a firmware para funcionarem como interface HID. Não tenho a intenção de mostrar como se cria a firmware, pois é uma coisa bem mais complexa, mas vc encontra facilmente para outros modelos de arduino na internet em outros projetos parecidos.
